AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Naming/FileName:
  Exclude:
    - lib/rubocop-stimulus_reflex.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
